package com.jhia.lab26.taskmaster.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.UUID;

@DynamoDBTable(tableName = "TaskMaster")
public class Task {
    private UUID id;
    private String title;
    private String description;
    private String assignee;
    private String status;
    private String imageURL;
    private String thumbnail;

    public Task() {};

    public Task(String title, String description, String assignee, String status) {
        this.title = title;
        this.description = description;
        this.assignee = assignee;
        this.status = status;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getAssignee() { return assignee; }

    public void setAssignee(String assignee) { this.assignee = assignee; }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) { this.status = status; }

    @DynamoDBAttribute
    public String getImageURL() {
        return imageURL;
    }

    @DynamoDBAttribute
    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String toggleCompletedStatus(String status) {
        this.status = status;
        return this.status;
    }

    public String assign(String assignee) {
        this.assignee = assignee;
        return this.assignee;
    }
}
